template_path: templates/openvpn.py

sceptre_user_data:
  key_pair: connorwilliams
  ami_id: ami-44aaf953
  instance_type: t2.micro
  volume_size: '8'
  vpn_admin_user: connor
  vpn_admin_pw: changeme

  # Default Tags
  application: OpenVPN
  owner_name: Connor Williams
  owner_email: connor.williams@cloudreach.com
