template_path: templates/security_group.py
sceptre_user_data:
  sg_name: OpenVPN
  rules:
    - to_port: 443
      from_port: 443
      ip_protocol: tcp
      cidr_ip: 0.0.0.0/0
    - to_port: 943
      from_port: 943
      ip_protocol: tcp
      cidr_ip: 0.0.0.0/0
    - to_port: 1194
      from_port: 1194
      ip_protocol: udp
      cidr_ip: 0.0.0.0/0

  vpc_id: !stack_output network::vpcid
  # Default Tags
  application: OpenVPN
  owner_name: Connor Williams
  owner_email: connor.williams@cloudreach.com
